name: list_product
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  http: ^0.13.5
  intl: ^0.18.0
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: '#ffffff'
  android: true
  ios: true
  image: lib/app/assets/images/logo.png

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

